web: 
  build: .
  command: sh -c 'npm install; npm start'
  ports: 
    - '4000:4000'
  volumes:
    - /home/oem/Desktop/TP2NSQL-master/receta/api:/api
  links:
    - 'db:redis'

db:
  image: redis
  ports:
    - "6379:6379"

